// Reads scripts/image-manifest.json, writes public/projects/<slug>/<out>.webp,
// and regenerates src/content/images.generated.ts with real sizes.
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import sharp from 'sharp'

interface Entry {
  slug: string
  source: string
  out: string
  alt: string
  caption?: string
  crop?: { left: number; top: number; width: number; height: number }
}

const root = resolve(import.meta.dirname, '..')
const manifest: Entry[] = JSON.parse(readFileSync(join(root, 'scripts/image-manifest.json'), 'utf8'))
const bySlug: Record<string, Array<{ src: string; alt: string; caption?: string; width: number; height: number }>> =
  {}

rmSync(join(root, 'public/projects'), { recursive: true, force: true })
for (const e of manifest) {
  const input = join(root, '.work/extracted', e.slug, e.source)
  const dir = join(root, 'public/projects', e.slug)
  mkdirSync(dir, { recursive: true })
  let img = sharp(input)
  if (e.crop) img = img.extract(e.crop)
  const info = await img
    .resize({ width: 1600, withoutEnlargement: true })
    .webp({ quality: 80 })
    .toFile(join(dir, `${e.out}.webp`))
  ;(bySlug[e.slug] ??= []).push({
    src: `/projects/${e.slug}/${e.out}.webp`,
    alt: e.alt,
    ...(e.caption ? { caption: e.caption } : {}),
    width: info.width,
    height: info.height,
  })
}
for (const list of Object.values(bySlug)) list.sort((a, b) => a.src.localeCompare(b.src))

const body = `// Generated by scripts/optimize-images.ts — do not edit by hand.
import type { ProjectImage } from './types'

export const projectImages: Record<string, ProjectImage[]> = ${JSON.stringify(bySlug, null, 2)}
`
writeFileSync(join(root, 'src/content/images.generated.ts'), body)
console.log(`optimize-images: ${manifest.length} images for ${Object.keys(bySlug).length} projects`)
